# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --use_buffer_bptt=False --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=False --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 --verbose=True
python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=True --time_steps=5 --batch_size=20 --num_units=500 --clip_gradients=False --learning_rate=0.001 --dataset='ptb' --runs=1 --verbose=True



##BPTT
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=True --time_steps=1 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=True --time_steps=5 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=True --time_steps=10 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=True --time_steps=20 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=True --time_steps=50 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &

# # wait

##NORMAL
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=20 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &

# wait
# ##HYBRID
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=20 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.01 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=False --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.01 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &

# wait

# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=1024 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=1 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=1 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=20 --state_updates_per_step=0 --batch_size=1 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=1 --num_units=200 --clip_gradients=True --learning_rate=0.01 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=20 --state_updates_per_step=0 --batch_size=1 --num_units=200 --clip_gradients=True --learning_rate=0.01 --output_learning_rate=0.01 --state_learning_rate=0.1 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=1 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --dataset='ptb' --runs=1 &

# wait

# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=20 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &

# wait

# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=50 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &

# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &

# wait
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=50 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &

# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
# python3 main.py --n_input=1 --n_classes=1 --use_lstm=True --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=20 --num_units=200 --clip_gradients=True --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.001 --dataset='ptb' --runs=1 &
