##BPTT
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=1 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=5 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=10 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=15 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait

# ##FPP
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait

# # ##NORMAL
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=20 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# wait

# # # ##HYBRID
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=2999 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=2999 --buffer_length=1000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=2999 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=2999 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=2999 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=2999 --buffer_length=1000 --updates_per_step=20 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# wait 

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=False --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=False --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=False --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --use_buffer_bptt=False --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait


# # wait
# # #PER
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=False --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=False --buffer_length=1000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=False --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=False --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# # wait

# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# # python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=True --use_hybrid=True --anneal_thresh_value=1.2 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# # wait
# # Parameter Sensitivity
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=100 --updates_per_step=50 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=False --buffer_length=10000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &


# wait
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=50 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=50 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=100 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=1000 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=2 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=2 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=2 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=100 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=10000 --updates_per_step=3 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=5 &

####LAMBDA
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=5 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=5 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=5 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=5 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=10 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=10 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=10 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=10 --runs=30 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.1 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0 --runs=30 &


# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.5 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.5 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.5 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=0.5 --runs=30 &


###LEARNING RATE
##BPTT
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=1 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=5 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=10 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=15 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=1 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=5 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=10 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=15 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=1 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=5 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=10 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=15 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=1 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=5 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=10 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=15 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=1 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=5 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=10 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=True --time_steps=15 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.001 --state_learning_rate=0.01 --runs=30 &


###FPP
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0001 --output_learning_rate=0.0001 --state_learning_rate=0.01 --lambda=1 --runs=30 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.0003 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.0003 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.0003 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.0003 --output_learning_rate=0.0003 --state_learning_rate=0.01 --lambda=1 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.003 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.003 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.003 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.003 --output_learning_rate=0.003 --state_learning_rate=0.01 --lambda=1 --runs=30 &

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.01 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.01 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.01 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.01 --output_learning_rate=0.01 --state_learning_rate=0.01 --lambda=1 --runs=30 &

# wait

# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.03 --output_learning_rate=0.03 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.03 --output_learning_rate=0.03 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.03 --output_learning_rate=0.03 --state_learning_rate=0.01 --lambda=1 --runs=30 &
# python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.03 --output_learning_rate=0.03 --state_learning_rate=0.01 --lambda=1 --runs=30 &

###STATE LR
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.01 --lambda=1 --runs=30 &

python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.03 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.03 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.03 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.03 --lambda=1 --runs=30 &

wait

python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.1 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.1 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.1 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.1 --lambda=1 --runs=30 &

python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.3 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.3 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.3 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.3 --lambda=1 --runs=30 &

wait

python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.001 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.001 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.001 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.001 --lambda=1 --runs=30 &

python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=1 --state_updates_per_step=0  --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.003 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=5 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.003 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=10 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.003 --lambda=1 --runs=30 &
python3 main.py --total_length=1000000 --use_bptt=False --use_prioritized_exp_replay=False --use_hybrid=True --anneal_thresh_value=1.0 --anneal_thresh_steps=499 --buffer_length=1000 --updates_per_step=15 --state_updates_per_step=0 --batch_size=100 --num_units=32 --dataset='stochastic_dataset' --learning_rate=0.001 --output_learning_rate=0.001 --state_learning_rate=0.003 --lambda=1 --runs=30 &

wait